server:
  port: 5555
  servlet:
    context-path:
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/just4feat
    username: postgres
    password: 1216830
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL10Dialect




#spring:
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#    hibernate:
#      ddl-auto: create-drop
#  datasource:
#    url: jdbc:postgresql://localhost:5432/just4feat?createDatabaseIfNotExist=true
#    username: postgres
#    password: 1216830
#    driverClassName: org.postgresql.Driver
#  jackson:
#    serialization:
#      indent-output: true
#server:
#  port: 5555
#  servlet:
#    context-path:
